# see rules at https://github.com/sasstools/sass-lint/tree/master/docs/rules

files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  empty-line-between-blocks: 0
  hex-length:
    - 1
    - style: long
  hex-notation: 0
  indentation:
    - 1
    - size: 4
  leading-zero:
    - 1
    - include: true
  nesting-depth:
    - 1
    - max-depth: 4
  no-ids: 0
  no-important: 0
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  property-sort-order: 0
  property-units:
    - 1
    - global:
        - rem
        - px
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - rad
        - ms
        - s
        - dpi
        - dppx
        - '%'
  quotes:
    - 1
    - style: double
  shorthand-values: 0